CREATE TABLE `music_analyses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`audioUrl` text,
	`audioKey` varchar(512),
	`bpm` float,
	`key` varchar(8),
	`mode` varchar(16),
	`keyFull` varchar(32),
	`timeSignature` varchar(16),
	`duration` varchar(16),
	`energyLevel` varchar(64),
	`dynamicRange` varchar(64),
	`brightness` varchar(64),
	`texture` varchar(64),
	`rhythmDensity` varchar(64),
	`moodTags` json,
	`genreHints` json,
	`generatedPrompts` json,
	`status` enum('pending','analyzing','done','error') NOT NULL DEFAULT 'pending',
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `music_analyses_id` PRIMARY KEY(`id`)
);
